### ISSUE TITLE
Please upload assembly.png, the image is missing

### ISSUE THREAD

**Issue by jmwang0117** [Video-as-Agent/VideoAgent#2]

**Comment by Whalesong-zrs** [comment]
You could find it in https://github.com/flow-diffusion/AVDC.

**Comment by TrickyJustice** [comment]
Since our work focuses on improving videos, an image input won’t demonstrate the results effectively. I’ve added a video that exhibits hallucination issues in the examples folder, which can be used as input. You don’t need to modify any code to input a video.
